repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        additional_dependencies:
        - pep8-naming
        - flake8-import-order
        - flake8-bugbear
        - flake8-builtins
        - flake8-quotes
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.711
#    hooks:
#      - id: mypy
